[package]
name = "libtest-with"
version = "0.7.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>", "Antonio Yang <yanganto>"]
edition = "2021"
rust-version = "1.60"

description = """
A slightly customized version of libtest-mimic,
such that it can be easier create a test runner for test-with
"""
documentation = "https://docs.rs/libtest-with"
repository = "https://github.com/yanganto/libtest-with"
license = "MIT/Apache-2.0"
keywords = ["libtest", "test", "built-in", "framework", "harness"]
categories = ["development-tools::testing", "development-tools::build-utils"]
readme = "README.md"

exclude = [".github"]

[dependencies]
clap = { version = "4.0.8", features = ["derive"] }
threadpool = "1.8.1"
termcolor = "1.0.5"
escape8259 = "0.5.2"

[dev-dependencies]
fastrand = "1.8.0"
pretty_assertions = "1.2.1"
